version: "3.8"
services:
  gpu-db:
    container_name: gpu-api-db
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: superStrongPassword
      POSTGRES_USER: dbUser
      POSTGRES_DB: gpuDb
    ports:
      - "5432:5432"
    volumes:
      - gpuDb:/var/lib/postgresql/data
volumes:
  gpuDb: