version: "3.8"
services:
  web:
    image: gpu-api:latest
    ports:
      - "80:8080"
    networks:
      - main
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CONFIG_NAME=application-prod.yaml
      - SPRING_CONFIG_LOCATION=file:///run/secrets/gpu-api-props.yaml
      - TZ=UTC
    secrets:
      - gpu-api-props.yaml
networks:
  main:
secrets:
  gpu-api-props.yaml:
    external: true
