version: "3.8"
services:
  web:
    build:
      context: .
    container_name: gpu-price
    ports:
      - "8080:8080"
    networks:
      - main
    environment:
      SPRING_PROFILES_ACTIVE: dev
      TZ: UTC
      REDIS_HOST: redis
      DB_USER: postgres
      DB_PASSWORD: superStrongPassword
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: gpuDb
    depends_on:
      - redis
      - db
  redis:
    image: redis:7.0.2-alpine
    ports:
      - "6379:6379"
    networks:
      - main
  db:
    image: postgres:14.4-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: superStrongPassword
      POSTGRES_DB: gpuDb
    volumes:
      - gpu-price-api-db:/var/lib/postgresql/data
    networks:
      - main
networks:
  main:
volumes:
  gpu-price-api-db: