version: "3.8"
services:
  web:
    build:
      context: .
    container_name: gpu-price-api
    ports:
      - "80:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - TZ=UTC
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - main
  redis:
    image: redis:7.0.2-alpine
    container_name: gpu-price-redis
    ports:
      - "6379:6379"
    networks:
      - main
networks:
  main:
