name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: VPS deploy
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{secrets.VPS_KEY}}
        port: ${{ secrets.VPS_PORT }}
        script: |
          cd github-build
          rm -rf gpu-price-api
          git clone https://github.com/doomedcat17/gpu-price-api.git
          cd gpu-price-api
          cp ${{secrets.PROPS_PATH}} src/main/resources/application-prod.yaml
          docker compose build --no-cache web
          docker compose up --force-recreate -d
