name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: VPS deploy
      run: |
        TEMP=$(mktemp)
        echo "${{ secrets.VPS_KEY }}" > $TEMP
        ssh -o 'StrictHostKeyChecking no' -i $TEMP -p "${{ secrets.VPS_PORT }}" "${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}" 'bash -s' < ./deploy.sh
